INSERT INTO categories (name) 
VALUES ('Planters'),
       ('Linens'),
       ('Halloween'),
       ('Kitsch'),
       ('Figurines'),
       ('Glass'),
       ('Mugs'),
       ('Jewelry'),
       ('Tins'),
       ('Vintage Plastic'),
       ('Pyrex'),
       ('Salt & Pepper Shakers'),
       ('Books'),
       ('Wall Art');

INSERT INTO products (name, description, condition, image, quantity, primary_color, era, height_in_inches, width_in_inches, date_added, price, category_name)
VALUES ('Vintage Dan River Floral Pillowcase Pair', 
        'This is a set of 2 vintage standard pillowcases by Dan River. They are a 50/50 poly cotton blend and have a lovely bold floral design.', 
        'great', 
        'https://images.unsplash.com/photo-1600876997455-4cafa4c419d1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=386&q=80', 
        1, 
        null, 
        '1970s', 
        null, 
        null, 
        NOW(), 
        14.00, 
        'Linens'),
       ('Vintage Handmade Macrame Owl Wall Hanging',
        'This is a handmade vintage macrame owl wall hanging. It has wooden bead eyes and is hung from 2 sticks.',
        'good', 
        null, 
        1, 
        'brown', 
        '1970s', 
        36, 
        null, 
        NOW(), 
        24.00, 
        'Wall Art'),
       ('Vintage Wooden Carved Owl Figure',
        'This is a vintage naturalistically carved owl figure from 1986. It is signed near the bottom and has a note on the bottom from the original owner that says the owl was purchased in the Smokies (the Great Smoky Mountains).',
        'good', 
        null, 
        1, 
        'brown', 
        '1980s', 
        null, 
        null, 
        NOW(), 
        8.00, 
        'Figurines'),
       ('Vintage Halloween Ceramic Tree Candleholder',
         'This is a vintage Halloween ceramic candleholder. It is a spooky tree with a face, accompanied by a jack o lantern and a trick or treating ghost.',
         'good', 
         null, 
         1, 
         'brown', 
         null, 
         7, 
         6, 
         NOW(), 
         16.00, 
         'Halloween'),
       ('Vintage Halloween Ceramic Trick or Treat Bag',
        'This is a vintage Halloween ceramic treat bag, made to look like a trick or treat candy sack! It is decorated with a witch,a black cat, a jack o lantern, and a ghost.',
        'good', 
        null, 
        1, 
        'brown', 
        null, 
        null, 
        null, 
        NOW(), 
        14.00, 
        'Halloween'),
       ('Vintage Enesco Lady Head Vase, Girl with Cat, Made in Japan',
        'This is a vintage midcentury ceramic lady head vase made by Enesco in Japan. This vase or planter depicts a young girl holding a white cat.',
        'good', 
        null, 
        1, 
        'pink', 
        'Midcentury', 
        null, 
        null, 
        NOW(), 
        48.00, 
        'Kitsch');

INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'joel@joelburton.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'joel@joelburton.com',
        TRUE);